export const GET_MOVIES = 'GET_MOVIES';
export const GET_MOVIES_FULFILLED = 'GET_MOVIES_FULFILLED';
export const GET_MOVIES_PENDING= 'GET_MOVIES_PENDING';

//Details
export const GET_MOVIE = 'GET_MOVIE';
export const GET_MOVIE_FULFILLED = 'GET_MOVIE_FULFILLED';
export const GET_MOVIE_PENDING= 'GET_MOVIE_PENDING';
